2023-12-22 14:28:29 - Neovide panicked with the message 'Focus Lost Failed: NeovimError(Some(0), "FocusLost Autocommands for \"*/home/refaelsh/repos/dotfiles/*\": Vim(append):Error executing lua callback: vim/_editor.lua:0: FocusLost Autocommands for \"*/home/refaelsh/repos/dotfiles/*\"..script nvim_exec2() called at FocusLost Autocommands for \"*/home/refaelsh/repos/dotfiles/*\":0: Vim:E492: Not an editor command: git add . && git commit -m \"WIP\" && git push\nstack traceback:\n\t[C]: in function 'nvim_exec2'\n\tvim/_editor.lua: in function 'cmd'\n\t/home/refaelsh/.config/nvim/init.lua:406: in function </home/refaelsh/.config/nvim/init.lua:405>")'. (File: src/bridge/ui_commands.rs; Line: 149, Column: 18)
   0: neovide::main::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: tokio::runtime::task::core::Core<T,S>::poll
   8: tokio::runtime::task::raw::poll
   9: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  10: tokio::runtime::task::raw::poll
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: std::sys::unix::thread::Thread::new::thread_start
  14: start_thread
  15: __GI___clone3

2023-12-22 14:28:29 - Neovide panicked with the message 'Focus Lost Failed: NeovimError(Some(0), "FocusLost Autocommands for \"*/home/refaelsh/repos/dotfiles/*\": Vim(append):Error executing lua callback: vim/_editor.lua:0: FocusLost Autocommands for \"*/home/refaelsh/repos/dotfiles/*\"..script nvim_exec2() called at FocusLost Autocommands for \"*/home/refaelsh/repos/dotfiles/*\":0: Vim:E492: Not an editor command: git add . && git commit -m \"WIP\" && git push\nstack traceback:\n\t[C]: in function 'nvim_exec2'\n\tvim/_editor.lua: in function 'cmd'\n\t/home/refaelsh/.config/nvim/init.lua:406: in function </home/refaelsh/.config/nvim/init.lua:405>")'. (File: src/bridge/ui_commands.rs; Line: 149, Column: 18)
   0: neovide::main::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: tokio::runtime::task::core::Core<T,S>::poll
   8: tokio::runtime::task::raw::poll
   9: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  10: tokio::runtime::task::raw::poll
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: std::sys::unix::thread::Thread::new::thread_start
  14: start_thread
  15: __GI___clone3

2023-12-22 14:28:29 - Neovide panicked with the message 'Focus Lost Failed: NeovimError(Some(0), "FocusLost Autocommands for \"*/home/refaelsh/repos/dotfiles/*\": Vim(append):Error executing lua callback: vim/_editor.lua:0: FocusLost Autocommands for \"*/home/refaelsh/repos/dotfiles/*\"..script nvim_exec2() called at FocusLost Autocommands for \"*/home/refaelsh/repos/dotfiles/*\":0: Vim:E492: Not an editor command: git add . && git commit -m \"WIP\" && git push\nstack traceback:\n\t[C]: in function 'nvim_exec2'\n\tvim/_editor.lua: in function 'cmd'\n\t/home/refaelsh/.config/nvim/init.lua:406: in function </home/refaelsh/.config/nvim/init.lua:405>")'. (File: src/bridge/ui_commands.rs; Line: 149, Column: 18)
   0: neovide::main::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: tokio::runtime::task::core::Core<T,S>::poll
   8: tokio::runtime::task::raw::poll
   9: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  10: tokio::runtime::task::raw::poll
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: std::sys::unix::thread::Thread::new::thread_start
  14: start_thread
  15: __GI___clone3

2023-12-22 14:28:29 - Neovide panicked with the message 'Focus Lost Failed: NeovimError(Some(0), "FocusLost Autocommands for \"*/home/refaelsh/repos/dotfiles/*\": Vim(append):Error executing lua callback: vim/_editor.lua:0: FocusLost Autocommands for \"*/home/refaelsh/repos/dotfiles/*\"..script nvim_exec2() called at FocusLost Autocommands for \"*/home/refaelsh/repos/dotfiles/*\":0: Vim:E492: Not an editor command: git add . && git commit -m \"WIP\" && git push\nstack traceback:\n\t[C]: in function 'nvim_exec2'\n\tvim/_editor.lua: in function 'cmd'\n\t/home/refaelsh/.config/nvim/init.lua:406: in function </home/refaelsh/.config/nvim/init.lua:405>")'. (File: src/bridge/ui_commands.rs; Line: 149, Column: 18)
   0: neovide::main::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: tokio::runtime::task::core::Core<T,S>::poll
   8: tokio::runtime::task::raw::poll
   9: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  10: tokio::runtime::task::raw::poll
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: std::sys::unix::thread::Thread::new::thread_start
  14: start_thread
  15: __GI___clone3

2023-12-22 14:28:32 - Neovide panicked with the message 'Focus Lost Failed: NeovimError(Some(0), "FocusLost Autocommands for \"*/home/refaelsh/repos/dotfiles/*\": Vim(append):Error executing lua callback: vim/_editor.lua:0: FocusLost Autocommands for \"*/home/refaelsh/repos/dotfiles/*\"..script nvim_exec2() called at FocusLost Autocommands for \"*/home/refaelsh/repos/dotfiles/*\":0: Vim:E492: Not an editor command: git add . && git commit -m \"WIP\" && git push\nstack traceback:\n\t[C]: in function 'nvim_exec2'\n\tvim/_editor.lua: in function 'cmd'\n\t/home/refaelsh/.config/nvim/init.lua:406: in function </home/refaelsh/.config/nvim/init.lua:405>")'. (File: src/bridge/ui_commands.rs; Line: 149, Column: 18)
   0: neovide::main::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: tokio::runtime::task::core::Core<T,S>::poll
   8: tokio::runtime::task::raw::poll
   9: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  10: tokio::runtime::task::raw::poll
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: std::sys::unix::thread::Thread::new::thread_start
  14: start_thread
  15: __GI___clone3

2023-12-22 14:29:43 - Neovide panicked with the message 'Focus Lost Failed: NeovimError(Some(0), "FocusLost Autocommands for \"*/home/refaelsh/repos/dotfiles/*\": Vim(append):Error executing lua callback: vim/_editor.lua:0: FocusLost Autocommands for \"*/home/refaelsh/repos/dotfiles/*\"..script nvim_exec2() called at FocusLost Autocommands for \"*/home/refaelsh/repos/dotfiles/*\":0: Vim:E492: Not an editor command: git add . && git commit -m \"WIP\" && git push\nstack traceback:\n\t[C]: in function 'nvim_exec2'\n\tvim/_editor.lua: in function 'cmd'\n\t/home/refaelsh/.config/nvim/init.lua:406: in function </home/refaelsh/.config/nvim/init.lua:405>")'. (File: src/bridge/ui_commands.rs; Line: 149, Column: 18)
   0: neovide::main::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: tokio::runtime::task::core::Core<T,S>::poll
   8: tokio::runtime::task::raw::poll
   9: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  10: tokio::runtime::task::raw::poll
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: std::sys::unix::thread::Thread::new::thread_start
  14: start_thread
  15: __GI___clone3

2023-12-23 15:44:05 - Neovide panicked with the message 'Focus Gained Failed: DecodeError(ReaderError(Custom { kind: UnexpectedEof, error: "EOF" }), "nvim_command")'. (File: src/bridge/ui_commands.rs; Line: 153, Column: 18)
   0: neovide::main::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: tokio::runtime::task::core::Core<T,S>::poll
   8: tokio::runtime::task::raw::poll
   9: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  10: tokio::runtime::task::raw::poll
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: std::sys::unix::thread::Thread::new::thread_start
  14: start_thread
  15: __GI___clone3

2023-12-23 15:44:11 - Neovide panicked with the message 'Focus Lost Failed: DecodeError(ReaderError(Custom { kind: UnexpectedEof, error: "EOF" }), "nvim_command")'. (File: src/bridge/ui_commands.rs; Line: 149, Column: 18)
   0: neovide::main::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: tokio::runtime::task::core::Core<T,S>::poll
   8: tokio::runtime::task::raw::poll
   9: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  10: tokio::runtime::task::raw::poll
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: std::sys::unix::thread::Thread::new::thread_start
  14: start_thread
  15: __GI___clone3

2023-12-23 15:44:11 - Neovide panicked with the message 'Focus Lost Failed: DecodeError(ReaderError(Custom { kind: UnexpectedEof, error: "EOF" }), "nvim_command")'. (File: src/bridge/ui_commands.rs; Line: 149, Column: 18)
   0: neovide::main::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: tokio::runtime::task::core::Core<T,S>::poll
   8: tokio::runtime::task::raw::poll
   9: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  10: tokio::runtime::task::raw::poll
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: std::sys::unix::thread::Thread::new::thread_start
  14: start_thread
  15: __GI___clone3

2023-12-23 15:44:11 - Neovide panicked with the message 'Focus Lost Failed: DecodeError(ReaderError(Custom { kind: UnexpectedEof, error: "EOF" }), "nvim_command")'. (File: src/bridge/ui_commands.rs; Line: 149, Column: 18)
   0: neovide::main::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: tokio::runtime::task::core::Core<T,S>::poll
   8: tokio::runtime::task::raw::poll
   9: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  10: tokio::runtime::task::raw::poll
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: std::sys::unix::thread::Thread::new::thread_start
  14: start_thread
  15: __GI___clone3

2023-12-23 16:18:25 - Neovide panicked with the message 'Focus Lost Failed: DecodeError(ReaderError(Custom { kind: UnexpectedEof, error: "EOF" }), "nvim_command")'. (File: src/bridge/ui_commands.rs; Line: 149, Column: 18)
   0: neovide::main::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: tokio::runtime::task::core::Core<T,S>::poll
   8: tokio::runtime::task::raw::poll
   9: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  10: tokio::runtime::task::raw::poll
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: std::sys::unix::thread::Thread::new::thread_start
  14: start_thread
  15: __GI___clone3

2023-12-23 20:16:33 - Neovide panicked with the message 'Focus Gained Failed: NeovimError(Some(0), "Vim:Error executing vim.schedule lua callback: ...e/pack/packer/start/gitsigns.nvim/lua/gitsigns/async.lua:85: The coroutine failed with this message: ...pack/packer/start/gitsigns.nvim/lua/gitsigns/watcher.lua:69: attempt to index a nil value\nstack traceback:\n\t...pack/packer/start/gitsigns.nvim/lua/gitsigns/watcher.lua: in function <...pack/packer/start/gitsigns.nvim/lua/gitsigns/watcher.lua:65>\nstack traceback:\n\t[C]: in function 'error'\n\t...e/pack/packer/start/gitsigns.nvim/lua/gitsigns/async.lua:85: in function 'cb'\n\t...e/pack/packer/start/gitsigns.nvim/lua/gitsigns/async.lua:127: in function <...e/pack/packer/start/gitsigns.nvim/lua/gitsigns/async.lua:126>")'. (File: src/bridge/ui_commands.rs; Line: 153, Column: 18)
   0: neovide::main::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: tokio::runtime::task::core::Core<T,S>::poll
   8: tokio::runtime::task::raw::poll
   9: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  10: tokio::runtime::task::raw::poll
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: std::sys::unix::thread::Thread::new::thread_start
  14: start_thread
  15: __GI___clone3

2023-12-23 20:22:08 - Neovide panicked with the message 'Focus Lost Failed: DecodeError(ReaderError(Custom { kind: UnexpectedEof, error: "EOF" }), "nvim_command")'. (File: src/bridge/ui_commands.rs; Line: 149, Column: 18)
   0: neovide::main::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: tokio::runtime::task::core::Core<T,S>::poll
   8: tokio::runtime::task::raw::poll
   9: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  10: tokio::runtime::task::raw::poll
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: std::sys::unix::thread::Thread::new::thread_start
  14: start_thread
  15: __GI___clone3

2023-12-23 21:36:21 - Neovide panicked with the message 'Focus Gained Failed: DecodeError(ReaderError(Custom { kind: UnexpectedEof, error: "EOF" }), "nvim_command")'. (File: src/bridge/ui_commands.rs; Line: 153, Column: 18)
   0: neovide::main::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: tokio::runtime::task::core::Core<T,S>::poll
   8: tokio::runtime::task::raw::poll
   9: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  10: tokio::runtime::task::raw::poll
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: std::sys::unix::thread::Thread::new::thread_start
  14: start_thread
  15: __GI___clone3

2023-12-25 17:46:23 - Neovide panicked with the message 'Focus Lost Failed: NeovimError(Some(0), "FocusLost Autocommands for \"*.norg\": Vim(append):Error executing lua callback: vim/_editor.lua:0: FocusLost Autocommands for \"*.norg\"..script nvim_exec2() called at FocusLost Autocommands for \"*.norg\":0: Vim:Error executing Lua callback: ...0.9.4/share/nvim/runtime/lua/vim/treesitter/language.lua:93: no parser for 'norg_meta' language, see :help treesitter-parsers\nstack traceback:\n\t[C]: in function 'error'\n\t...0.9.4/share/nvim/runtime/lua/vim/treesitter/language.lua:93: in function 'add'\n\t...ed-0.9.4/share/nvim/runtime/lua/vim/treesitter/query.lua:252: in function 'ts_parse_query'\n\t...ua/neorg/modules/core/integrations/treesitter/module.lua:658: in function 'get_document_metadata'\n\t...nvim/lazy/neorg/lua/neorg/modules/core/tangle/module.lua:212: in function 'tangle'\n\t...nvim/lazy/neorg/lua/neorg/modules/core/tangle/module.lua:421: in function 'on_event'\n\t.../.local/share/nvim/lazy/neorg/lua/neorg/core/modules.lua:709: in function 'broadcast_event'\n\t...im/lazy/neorg/lua/neorg/modules/core/neorgcmd/module.lua:286: in function <...im/lazy/neorg/lua/neorg/modules/core/neorgcmd/module.lua:193>\n\t[C]: in function 'nvim_exec2'\n\tvim/_editor.lua: in function 'cmd'\n\t/home/refaelsh/.config/nvim/init.lua:125: in function </home/refaelsh/.config/nvim/init.lua:124>\nstack traceback:\n\t[C]: in function 'nvim_exec2'\n\tvim/_editor.lua: in function 'cmd'\n\t/home/refaelsh/.config/nvim/init.lua:125: in function </home/refaelsh/.config/nvim/init.lua:124>")'. (File: src/bridge/ui_commands.rs; Line: 149, Column: 18)
   0: neovide::main::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: tokio::runtime::task::core::Core<T,S>::poll
   8: tokio::runtime::task::raw::poll
   9: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  10: tokio::runtime::task::raw::poll
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: std::sys::unix::thread::Thread::new::thread_start
  14: start_thread
  15: __GI___clone3

2023-12-25 17:46:32 - Neovide panicked with the message 'Focus Lost Failed: NeovimError(Some(0), "FocusLost Autocommands for \"*.norg\": Vim(append):Error executing lua callback: vim/_editor.lua:0: FocusLost Autocommands for \"*.norg\"..script nvim_exec2() called at FocusLost Autocommands for \"*.norg\":0: Vim:Error executing Lua callback: ...0.9.4/share/nvim/runtime/lua/vim/treesitter/language.lua:93: no parser for 'norg_meta' language, see :help treesitter-parsers\nstack traceback:\n\t[C]: in function 'error'\n\t...0.9.4/share/nvim/runtime/lua/vim/treesitter/language.lua:93: in function 'add'\n\t...ed-0.9.4/share/nvim/runtime/lua/vim/treesitter/query.lua:252: in function 'ts_parse_query'\n\t...ua/neorg/modules/core/integrations/treesitter/module.lua:658: in function 'get_document_metadata'\n\t...nvim/lazy/neorg/lua/neorg/modules/core/tangle/module.lua:212: in function 'tangle'\n\t...nvim/lazy/neorg/lua/neorg/modules/core/tangle/module.lua:421: in function 'on_event'\n\t.../.local/share/nvim/lazy/neorg/lua/neorg/core/modules.lua:709: in function 'broadcast_event'\n\t...im/lazy/neorg/lua/neorg/modules/core/neorgcmd/module.lua:286: in function <...im/lazy/neorg/lua/neorg/modules/core/neorgcmd/module.lua:193>\n\t[C]: in function 'nvim_exec2'\n\tvim/_editor.lua: in function 'cmd'\n\t/home/refaelsh/.config/nvim/init.lua:125: in function </home/refaelsh/.config/nvim/init.lua:124>\nstack traceback:\n\t[C]: in function 'nvim_exec2'\n\tvim/_editor.lua: in function 'cmd'\n\t/home/refaelsh/.config/nvim/init.lua:125: in function </home/refaelsh/.config/nvim/init.lua:124>")'. (File: src/bridge/ui_commands.rs; Line: 149, Column: 18)
   0: neovide::main::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: tokio::runtime::task::core::Core<T,S>::poll
   8: tokio::runtime::task::raw::poll
   9: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  10: tokio::runtime::task::raw::poll
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: std::sys::unix::thread::Thread::new::thread_start
  14: start_thread
  15: __GI___clone3

2023-12-25 17:48:17 - Neovide panicked with the message 'Focus Lost Failed: NeovimError(Some(0), "FocusLost Autocommands for \"*.norg\": Vim(append):Error executing lua callback: vim/_editor.lua:0: FocusLost Autocommands for \"*.norg\"..script nvim_exec2() called at FocusLost Autocommands for \"*.norg\":0: Vim:Error executing Lua callback: ...0.9.4/share/nvim/runtime/lua/vim/treesitter/language.lua:93: no parser for 'norg_meta' language, see :help treesitter-parsers\nstack traceback:\n\t[C]: in function 'error'\n\t...0.9.4/share/nvim/runtime/lua/vim/treesitter/language.lua:93: in function 'add'\n\t...ed-0.9.4/share/nvim/runtime/lua/vim/treesitter/query.lua:252: in function 'ts_parse_query'\n\t...ua/neorg/modules/core/integrations/treesitter/module.lua:658: in function 'get_document_metadata'\n\t...nvim/lazy/neorg/lua/neorg/modules/core/tangle/module.lua:212: in function 'tangle'\n\t...nvim/lazy/neorg/lua/neorg/modules/core/tangle/module.lua:421: in function 'on_event'\n\t.../.local/share/nvim/lazy/neorg/lua/neorg/core/modules.lua:709: in function 'broadcast_event'\n\t...im/lazy/neorg/lua/neorg/modules/core/neorgcmd/module.lua:286: in function <...im/lazy/neorg/lua/neorg/modules/core/neorgcmd/module.lua:193>\n\t[C]: in function 'nvim_exec2'\n\tvim/_editor.lua: in function 'cmd'\n\t/home/refaelsh/.config/nvim/init.lua:125: in function </home/refaelsh/.config/nvim/init.lua:124>\nstack traceback:\n\t[C]: in function 'nvim_exec2'\n\tvim/_editor.lua: in function 'cmd'\n\t/home/refaelsh/.config/nvim/init.lua:125: in function </home/refaelsh/.config/nvim/init.lua:124>")'. (File: src/bridge/ui_commands.rs; Line: 149, Column: 18)
   0: neovide::main::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: tokio::runtime::task::core::Core<T,S>::poll
   8: tokio::runtime::task::raw::poll
   9: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  10: tokio::runtime::task::raw::poll
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: std::sys::unix::thread::Thread::new::thread_start
  14: start_thread
  15: __GI___clone3

2023-12-25 17:48:20 - Neovide panicked with the message 'Focus Lost Failed: NeovimError(Some(0), "FocusLost Autocommands for \"*.norg\": Vim(append):Error executing lua callback: vim/_editor.lua:0: FocusLost Autocommands for \"*.norg\"..script nvim_exec2() called at FocusLost Autocommands for \"*.norg\":0: Vim:Error executing Lua callback: ...0.9.4/share/nvim/runtime/lua/vim/treesitter/language.lua:93: no parser for 'norg_meta' language, see :help treesitter-parsers\nstack traceback:\n\t[C]: in function 'error'\n\t...0.9.4/share/nvim/runtime/lua/vim/treesitter/language.lua:93: in function 'add'\n\t...ed-0.9.4/share/nvim/runtime/lua/vim/treesitter/query.lua:252: in function 'ts_parse_query'\n\t...ua/neorg/modules/core/integrations/treesitter/module.lua:658: in function 'get_document_metadata'\n\t...nvim/lazy/neorg/lua/neorg/modules/core/tangle/module.lua:212: in function 'tangle'\n\t...nvim/lazy/neorg/lua/neorg/modules/core/tangle/module.lua:421: in function 'on_event'\n\t.../.local/share/nvim/lazy/neorg/lua/neorg/core/modules.lua:709: in function 'broadcast_event'\n\t...im/lazy/neorg/lua/neorg/modules/core/neorgcmd/module.lua:286: in function <...im/lazy/neorg/lua/neorg/modules/core/neorgcmd/module.lua:193>\n\t[C]: in function 'nvim_exec2'\n\tvim/_editor.lua: in function 'cmd'\n\t/home/refaelsh/.config/nvim/init.lua:125: in function </home/refaelsh/.config/nvim/init.lua:124>\nstack traceback:\n\t[C]: in function 'nvim_exec2'\n\tvim/_editor.lua: in function 'cmd'\n\t/home/refaelsh/.config/nvim/init.lua:125: in function </home/refaelsh/.config/nvim/init.lua:124>")'. (File: src/bridge/ui_commands.rs; Line: 149, Column: 18)
   0: neovide::main::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: tokio::runtime::task::core::Core<T,S>::poll
   8: tokio::runtime::task::raw::poll
   9: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  10: tokio::runtime::task::raw::poll
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: std::sys::unix::thread::Thread::new::thread_start
  14: start_thread
  15: __GI___clone3

2023-12-25 17:48:45 - Neovide panicked with the message 'Focus Lost Failed: NeovimError(Some(0), "FocusLost Autocommands for \"*.norg\": Vim(append):Error executing lua callback: vim/_editor.lua:0: FocusLost Autocommands for \"*.norg\"..script nvim_exec2() called at FocusLost Autocommands for \"*.norg\":0: Vim:Error executing Lua callback: ...0.9.4/share/nvim/runtime/lua/vim/treesitter/language.lua:93: no parser for 'norg_meta' language, see :help treesitter-parsers\nstack traceback:\n\t[C]: in function 'error'\n\t...0.9.4/share/nvim/runtime/lua/vim/treesitter/language.lua:93: in function 'add'\n\t...ed-0.9.4/share/nvim/runtime/lua/vim/treesitter/query.lua:252: in function 'ts_parse_query'\n\t...ua/neorg/modules/core/integrations/treesitter/module.lua:658: in function 'get_document_metadata'\n\t...nvim/lazy/neorg/lua/neorg/modules/core/tangle/module.lua:212: in function 'tangle'\n\t...nvim/lazy/neorg/lua/neorg/modules/core/tangle/module.lua:421: in function 'on_event'\n\t.../.local/share/nvim/lazy/neorg/lua/neorg/core/modules.lua:709: in function 'broadcast_event'\n\t...im/lazy/neorg/lua/neorg/modules/core/neorgcmd/module.lua:286: in function <...im/lazy/neorg/lua/neorg/modules/core/neorgcmd/module.lua:193>\n\t[C]: in function 'nvim_exec2'\n\tvim/_editor.lua: in function 'cmd'\n\t/home/refaelsh/.config/nvim/init.lua:125: in function </home/refaelsh/.config/nvim/init.lua:124>\nstack traceback:\n\t[C]: in function 'nvim_exec2'\n\tvim/_editor.lua: in function 'cmd'\n\t/home/refaelsh/.config/nvim/init.lua:125: in function </home/refaelsh/.config/nvim/init.lua:124>")'. (File: src/bridge/ui_commands.rs; Line: 149, Column: 18)
   0: neovide::main::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: tokio::runtime::task::core::Core<T,S>::poll
   8: tokio::runtime::task::raw::poll
   9: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  10: tokio::runtime::task::raw::poll
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: std::sys::unix::thread::Thread::new::thread_start
  14: start_thread
  15: __GI___clone3

2023-12-25 17:48:45 - Neovide panicked with the message 'Focus Lost Failed: NeovimError(Some(0), "FocusLost Autocommands for \"*.norg\": Vim(append):Error executing lua callback: vim/_editor.lua:0: FocusLost Autocommands for \"*.norg\"..script nvim_exec2() called at FocusLost Autocommands for \"*.norg\":0: Vim:Error executing Lua callback: ...0.9.4/share/nvim/runtime/lua/vim/treesitter/language.lua:93: no parser for 'norg_meta' language, see :help treesitter-parsers\nstack traceback:\n\t[C]: in function 'error'\n\t...0.9.4/share/nvim/runtime/lua/vim/treesitter/language.lua:93: in function 'add'\n\t...ed-0.9.4/share/nvim/runtime/lua/vim/treesitter/query.lua:252: in function 'ts_parse_query'\n\t...ua/neorg/modules/core/integrations/treesitter/module.lua:658: in function 'get_document_metadata'\n\t...nvim/lazy/neorg/lua/neorg/modules/core/tangle/module.lua:212: in function 'tangle'\n\t...nvim/lazy/neorg/lua/neorg/modules/core/tangle/module.lua:421: in function 'on_event'\n\t.../.local/share/nvim/lazy/neorg/lua/neorg/core/modules.lua:709: in function 'broadcast_event'\n\t...im/lazy/neorg/lua/neorg/modules/core/neorgcmd/module.lua:286: in function <...im/lazy/neorg/lua/neorg/modules/core/neorgcmd/module.lua:193>\n\t[C]: in function 'nvim_exec2'\n\tvim/_editor.lua: in function 'cmd'\n\t/home/refaelsh/.config/nvim/init.lua:125: in function </home/refaelsh/.config/nvim/init.lua:124>\nstack traceback:\n\t[C]: in function 'nvim_exec2'\n\tvim/_editor.lua: in function 'cmd'\n\t/home/refaelsh/.config/nvim/init.lua:125: in function </home/refaelsh/.config/nvim/init.lua:124>")'. (File: src/bridge/ui_commands.rs; Line: 149, Column: 18)
   0: neovide::main::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: tokio::runtime::task::core::Core<T,S>::poll
   8: tokio::runtime::task::raw::poll
   9: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  10: tokio::runtime::task::raw::poll
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: std::sys::unix::thread::Thread::new::thread_start
  14: start_thread
  15: __GI___clone3

2023-12-25 17:48:48 - Neovide panicked with the message 'Focus Lost Failed: NeovimError(Some(0), "FocusLost Autocommands for \"*.norg\": Vim(append):Error executing lua callback: vim/_editor.lua:0: FocusLost Autocommands for \"*.norg\"..script nvim_exec2() called at FocusLost Autocommands for \"*.norg\":0: Vim:Error executing Lua callback: ...0.9.4/share/nvim/runtime/lua/vim/treesitter/language.lua:93: no parser for 'norg_meta' language, see :help treesitter-parsers\nstack traceback:\n\t[C]: in function 'error'\n\t...0.9.4/share/nvim/runtime/lua/vim/treesitter/language.lua:93: in function 'add'\n\t...ed-0.9.4/share/nvim/runtime/lua/vim/treesitter/query.lua:252: in function 'ts_parse_query'\n\t...ua/neorg/modules/core/integrations/treesitter/module.lua:658: in function 'get_document_metadata'\n\t...nvim/lazy/neorg/lua/neorg/modules/core/tangle/module.lua:212: in function 'tangle'\n\t...nvim/lazy/neorg/lua/neorg/modules/core/tangle/module.lua:421: in function 'on_event'\n\t.../.local/share/nvim/lazy/neorg/lua/neorg/core/modules.lua:709: in function 'broadcast_event'\n\t...im/lazy/neorg/lua/neorg/modules/core/neorgcmd/module.lua:286: in function <...im/lazy/neorg/lua/neorg/modules/core/neorgcmd/module.lua:193>\n\t[C]: in function 'nvim_exec2'\n\tvim/_editor.lua: in function 'cmd'\n\t/home/refaelsh/.config/nvim/init.lua:125: in function </home/refaelsh/.config/nvim/init.lua:124>\nstack traceback:\n\t[C]: in function 'nvim_exec2'\n\tvim/_editor.lua: in function 'cmd'\n\t/home/refaelsh/.config/nvim/init.lua:125: in function </home/refaelsh/.config/nvim/init.lua:124>")'. (File: src/bridge/ui_commands.rs; Line: 149, Column: 18)
   0: neovide::main::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: tokio::runtime::task::core::Core<T,S>::poll
   8: tokio::runtime::task::raw::poll
   9: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  10: tokio::runtime::task::raw::poll
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: std::sys::unix::thread::Thread::new::thread_start
  14: start_thread
  15: __GI___clone3

2023-12-25 17:48:51 - Neovide panicked with the message 'Focus Lost Failed: NeovimError(Some(0), "FocusLost Autocommands for \"*.norg\": Vim(append):Error executing lua callback: vim/_editor.lua:0: FocusLost Autocommands for \"*.norg\"..script nvim_exec2() called at FocusLost Autocommands for \"*.norg\":0: Vim:Error executing Lua callback: ...0.9.4/share/nvim/runtime/lua/vim/treesitter/language.lua:93: no parser for 'norg_meta' language, see :help treesitter-parsers\nstack traceback:\n\t[C]: in function 'error'\n\t...0.9.4/share/nvim/runtime/lua/vim/treesitter/language.lua:93: in function 'add'\n\t...ed-0.9.4/share/nvim/runtime/lua/vim/treesitter/query.lua:252: in function 'ts_parse_query'\n\t...ua/neorg/modules/core/integrations/treesitter/module.lua:658: in function 'get_document_metadata'\n\t...nvim/lazy/neorg/lua/neorg/modules/core/tangle/module.lua:212: in function 'tangle'\n\t...nvim/lazy/neorg/lua/neorg/modules/core/tangle/module.lua:421: in function 'on_event'\n\t.../.local/share/nvim/lazy/neorg/lua/neorg/core/modules.lua:709: in function 'broadcast_event'\n\t...im/lazy/neorg/lua/neorg/modules/core/neorgcmd/module.lua:286: in function <...im/lazy/neorg/lua/neorg/modules/core/neorgcmd/module.lua:193>\n\t[C]: in function 'nvim_exec2'\n\tvim/_editor.lua: in function 'cmd'\n\t/home/refaelsh/.config/nvim/init.lua:125: in function </home/refaelsh/.config/nvim/init.lua:124>\nstack traceback:\n\t[C]: in function 'nvim_exec2'\n\tvim/_editor.lua: in function 'cmd'\n\t/home/refaelsh/.config/nvim/init.lua:125: in function </home/refaelsh/.config/nvim/init.lua:124>")'. (File: src/bridge/ui_commands.rs; Line: 149, Column: 18)
   0: neovide::main::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: tokio::runtime::task::core::Core<T,S>::poll
   8: tokio::runtime::task::raw::poll
   9: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  10: tokio::runtime::task::raw::poll
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: std::sys::unix::thread::Thread::new::thread_start
  14: start_thread
  15: __GI___clone3

2023-12-25 17:49:59 - Neovide panicked with the message 'Focus Lost Failed: NeovimError(Some(0), "FocusLost Autocommands for \"*.norg\": Vim(append):Error executing lua callback: vim/_editor.lua:0: FocusLost Autocommands for \"*.norg\"..script nvim_exec2() called at FocusLost Autocommands for \"*.norg\":0: Vim:Error executing Lua callback: ...0.9.4/share/nvim/runtime/lua/vim/treesitter/language.lua:93: no parser for 'norg_meta' language, see :help treesitter-parsers\nstack traceback:\n\t[C]: in function 'error'\n\t...0.9.4/share/nvim/runtime/lua/vim/treesitter/language.lua:93: in function 'add'\n\t...ed-0.9.4/share/nvim/runtime/lua/vim/treesitter/query.lua:252: in function 'ts_parse_query'\n\t...ua/neorg/modules/core/integrations/treesitter/module.lua:658: in function 'get_document_metadata'\n\t...nvim/lazy/neorg/lua/neorg/modules/core/tangle/module.lua:212: in function 'tangle'\n\t...nvim/lazy/neorg/lua/neorg/modules/core/tangle/module.lua:421: in function 'on_event'\n\t.../.local/share/nvim/lazy/neorg/lua/neorg/core/modules.lua:709: in function 'broadcast_event'\n\t...im/lazy/neorg/lua/neorg/modules/core/neorgcmd/module.lua:286: in function <...im/lazy/neorg/lua/neorg/modules/core/neorgcmd/module.lua:193>\n\t[C]: in function 'nvim_exec2'\n\tvim/_editor.lua: in function 'cmd'\n\t/home/refaelsh/.config/nvim/init.lua:125: in function </home/refaelsh/.config/nvim/init.lua:124>\nstack traceback:\n\t[C]: in function 'nvim_exec2'\n\tvim/_editor.lua: in function 'cmd'\n\t/home/refaelsh/.config/nvim/init.lua:125: in function </home/refaelsh/.config/nvim/init.lua:124>")'. (File: src/bridge/ui_commands.rs; Line: 149, Column: 18)
   0: neovide::main::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: tokio::runtime::task::core::Core<T,S>::poll
   8: tokio::runtime::task::raw::poll
   9: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  10: tokio::runtime::task::raw::poll
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: std::sys::unix::thread::Thread::new::thread_start
  14: start_thread
  15: __GI___clone3

2023-12-25 17:50:01 - Neovide panicked with the message 'Focus Lost Failed: NeovimError(Some(0), "FocusLost Autocommands for \"*.norg\": Vim(append):Error executing lua callback: vim/_editor.lua:0: FocusLost Autocommands for \"*.norg\"..script nvim_exec2() called at FocusLost Autocommands for \"*.norg\":0: Vim:Error executing Lua callback: ...0.9.4/share/nvim/runtime/lua/vim/treesitter/language.lua:93: no parser for 'norg_meta' language, see :help treesitter-parsers\nstack traceback:\n\t[C]: in function 'error'\n\t...0.9.4/share/nvim/runtime/lua/vim/treesitter/language.lua:93: in function 'add'\n\t...ed-0.9.4/share/nvim/runtime/lua/vim/treesitter/query.lua:252: in function 'ts_parse_query'\n\t...ua/neorg/modules/core/integrations/treesitter/module.lua:658: in function 'get_document_metadata'\n\t...nvim/lazy/neorg/lua/neorg/modules/core/tangle/module.lua:212: in function 'tangle'\n\t...nvim/lazy/neorg/lua/neorg/modules/core/tangle/module.lua:421: in function 'on_event'\n\t.../.local/share/nvim/lazy/neorg/lua/neorg/core/modules.lua:709: in function 'broadcast_event'\n\t...im/lazy/neorg/lua/neorg/modules/core/neorgcmd/module.lua:286: in function <...im/lazy/neorg/lua/neorg/modules/core/neorgcmd/module.lua:193>\n\t[C]: in function 'nvim_exec2'\n\tvim/_editor.lua: in function 'cmd'\n\t/home/refaelsh/.config/nvim/init.lua:125: in function </home/refaelsh/.config/nvim/init.lua:124>\nstack traceback:\n\t[C]: in function 'nvim_exec2'\n\tvim/_editor.lua: in function 'cmd'\n\t/home/refaelsh/.config/nvim/init.lua:125: in function </home/refaelsh/.config/nvim/init.lua:124>")'. (File: src/bridge/ui_commands.rs; Line: 149, Column: 18)
   0: neovide::main::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: tokio::runtime::task::core::Core<T,S>::poll
   8: tokio::runtime::task::raw::poll
   9: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  10: tokio::runtime::task::raw::poll
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: std::sys::unix::thread::Thread::new::thread_start
  14: start_thread
  15: __GI___clone3

2023-12-25 17:50:04 - Neovide panicked with the message 'Focus Lost Failed: NeovimError(Some(0), "FocusLost Autocommands for \"*.norg\": Vim(append):Error executing lua callback: vim/_editor.lua:0: FocusLost Autocommands for \"*.norg\"..script nvim_exec2() called at FocusLost Autocommands for \"*.norg\":0: Vim:Error executing Lua callback: ...0.9.4/share/nvim/runtime/lua/vim/treesitter/language.lua:93: no parser for 'norg_meta' language, see :help treesitter-parsers\nstack traceback:\n\t[C]: in function 'error'\n\t...0.9.4/share/nvim/runtime/lua/vim/treesitter/language.lua:93: in function 'add'\n\t...ed-0.9.4/share/nvim/runtime/lua/vim/treesitter/query.lua:252: in function 'ts_parse_query'\n\t...ua/neorg/modules/core/integrations/treesitter/module.lua:658: in function 'get_document_metadata'\n\t...nvim/lazy/neorg/lua/neorg/modules/core/tangle/module.lua:212: in function 'tangle'\n\t...nvim/lazy/neorg/lua/neorg/modules/core/tangle/module.lua:421: in function 'on_event'\n\t.../.local/share/nvim/lazy/neorg/lua/neorg/core/modules.lua:709: in function 'broadcast_event'\n\t...im/lazy/neorg/lua/neorg/modules/core/neorgcmd/module.lua:286: in function <...im/lazy/neorg/lua/neorg/modules/core/neorgcmd/module.lua:193>\n\t[C]: in function 'nvim_exec2'\n\tvim/_editor.lua: in function 'cmd'\n\t/home/refaelsh/.config/nvim/init.lua:125: in function </home/refaelsh/.config/nvim/init.lua:124>\nstack traceback:\n\t[C]: in function 'nvim_exec2'\n\tvim/_editor.lua: in function 'cmd'\n\t/home/refaelsh/.config/nvim/init.lua:125: in function </home/refaelsh/.config/nvim/init.lua:124>")'. (File: src/bridge/ui_commands.rs; Line: 149, Column: 18)
   0: neovide::main::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: tokio::runtime::task::core::Core<T,S>::poll
   8: tokio::runtime::task::raw::poll
   9: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  10: tokio::runtime::task::raw::poll
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: std::sys::unix::thread::Thread::new::thread_start
  14: start_thread
  15: __GI___clone3

2023-12-25 17:50:07 - Neovide panicked with the message 'Focus Lost Failed: NeovimError(Some(0), "FocusLost Autocommands for \"*.norg\": Vim(append):Error executing lua callback: vim/_editor.lua:0: FocusLost Autocommands for \"*.norg\"..script nvim_exec2() called at FocusLost Autocommands for \"*.norg\":0: Vim:Error executing Lua callback: ...0.9.4/share/nvim/runtime/lua/vim/treesitter/language.lua:93: no parser for 'norg_meta' language, see :help treesitter-parsers\nstack traceback:\n\t[C]: in function 'error'\n\t...0.9.4/share/nvim/runtime/lua/vim/treesitter/language.lua:93: in function 'add'\n\t...ed-0.9.4/share/nvim/runtime/lua/vim/treesitter/query.lua:252: in function 'ts_parse_query'\n\t...ua/neorg/modules/core/integrations/treesitter/module.lua:658: in function 'get_document_metadata'\n\t...nvim/lazy/neorg/lua/neorg/modules/core/tangle/module.lua:212: in function 'tangle'\n\t...nvim/lazy/neorg/lua/neorg/modules/core/tangle/module.lua:421: in function 'on_event'\n\t.../.local/share/nvim/lazy/neorg/lua/neorg/core/modules.lua:709: in function 'broadcast_event'\n\t...im/lazy/neorg/lua/neorg/modules/core/neorgcmd/module.lua:286: in function <...im/lazy/neorg/lua/neorg/modules/core/neorgcmd/module.lua:193>\n\t[C]: in function 'nvim_exec2'\n\tvim/_editor.lua: in function 'cmd'\n\t/home/refaelsh/.config/nvim/init.lua:125: in function </home/refaelsh/.config/nvim/init.lua:124>\nstack traceback:\n\t[C]: in function 'nvim_exec2'\n\tvim/_editor.lua: in function 'cmd'\n\t/home/refaelsh/.config/nvim/init.lua:125: in function </home/refaelsh/.config/nvim/init.lua:124>")'. (File: src/bridge/ui_commands.rs; Line: 149, Column: 18)
   0: neovide::main::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: tokio::runtime::task::core::Core<T,S>::poll
   8: tokio::runtime::task::raw::poll
   9: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  10: tokio::runtime::task::raw::poll
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: std::sys::unix::thread::Thread::new::thread_start
  14: start_thread
  15: __GI___clone3

2023-12-25 17:50:51 - Neovide panicked with the message 'Focus Lost Failed: NeovimError(Some(0), "FocusLost Autocommands for \"*.norg\": Vim(append):Error executing lua callback: vim/_editor.lua:0: FocusLost Autocommands for \"*.norg\"..script nvim_exec2() called at FocusLost Autocommands for \"*.norg\":0: Vim:Error executing Lua callback: ...0.9.4/share/nvim/runtime/lua/vim/treesitter/language.lua:93: no parser for 'norg_meta' language, see :help treesitter-parsers\nstack traceback:\n\t[C]: in function 'error'\n\t...0.9.4/share/nvim/runtime/lua/vim/treesitter/language.lua:93: in function 'add'\n\t...ed-0.9.4/share/nvim/runtime/lua/vim/treesitter/query.lua:252: in function 'ts_parse_query'\n\t...ua/neorg/modules/core/integrations/treesitter/module.lua:658: in function 'get_document_metadata'\n\t...nvim/lazy/neorg/lua/neorg/modules/core/tangle/module.lua:212: in function 'tangle'\n\t...nvim/lazy/neorg/lua/neorg/modules/core/tangle/module.lua:421: in function 'on_event'\n\t.../.local/share/nvim/lazy/neorg/lua/neorg/core/modules.lua:709: in function 'broadcast_event'\n\t...im/lazy/neorg/lua/neorg/modules/core/neorgcmd/module.lua:286: in function <...im/lazy/neorg/lua/neorg/modules/core/neorgcmd/module.lua:193>\n\t[C]: in function 'nvim_exec2'\n\tvim/_editor.lua: in function 'cmd'\n\t/home/refaelsh/.config/nvim/init.lua:125: in function </home/refaelsh/.config/nvim/init.lua:124>\nstack traceback:\n\t[C]: in function 'nvim_exec2'\n\tvim/_editor.lua: in function 'cmd'\n\t/home/refaelsh/.config/nvim/init.lua:125: in function </home/refaelsh/.config/nvim/init.lua:124>")'. (File: src/bridge/ui_commands.rs; Line: 149, Column: 18)
   0: neovide::main::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: tokio::runtime::task::core::Core<T,S>::poll
   8: tokio::runtime::task::raw::poll
   9: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  10: tokio::runtime::task::raw::poll
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: std::sys::unix::thread::Thread::new::thread_start
  14: start_thread
  15: __GI___clone3

2023-12-25 19:13:28 - Neovide panicked with the message 'Focus Lost Failed: NeovimError(Some(0), "FocusLost Autocommands for \"*.norg\": Vim(append):Error executing lua callback: vim/_editor.lua:0: FocusLost Autocommands for \"*.norg\"..script nvim_exec2() called at FocusLost Autocommands for \"*.norg\":0: Vim:E492: Not an editor command: Neorg tangle current-file\nstack traceback:\n\t[C]: in function 'nvim_exec2'\n\tvim/_editor.lua: in function 'cmd'\n\t/home/refaelsh/.config/nvim/init.lua:120: in function </home/refaelsh/.config/nvim/init.lua:119>")'. (File: src/bridge/ui_commands.rs; Line: 149, Column: 18)
   0: neovide::main::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: tokio::runtime::task::core::Core<T,S>::poll
   8: tokio::runtime::task::raw::poll
   9: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  10: tokio::runtime::task::raw::poll
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: std::sys::unix::thread::Thread::new::thread_start
  14: start_thread
  15: __GI___clone3

2023-12-25 19:13:31 - Neovide panicked with the message 'Focus Lost Failed: NeovimError(Some(0), "FocusLost Autocommands for \"*.norg\": Vim(append):Error executing lua callback: vim/_editor.lua:0: FocusLost Autocommands for \"*.norg\"..script nvim_exec2() called at FocusLost Autocommands for \"*.norg\":0: Vim:E492: Not an editor command: Neorg tangle current-file\nstack traceback:\n\t[C]: in function 'nvim_exec2'\n\tvim/_editor.lua: in function 'cmd'\n\t/home/refaelsh/.config/nvim/init.lua:120: in function </home/refaelsh/.config/nvim/init.lua:119>")'. (File: src/bridge/ui_commands.rs; Line: 149, Column: 18)
   0: neovide::main::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: tokio::runtime::task::core::Core<T,S>::poll
   8: tokio::runtime::task::raw::poll
   9: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  10: tokio::runtime::task::raw::poll
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: std::sys::unix::thread::Thread::new::thread_start
  14: start_thread
  15: __GI___clone3

2023-12-25 19:13:33 - Neovide panicked with the message 'Focus Lost Failed: NeovimError(Some(0), "FocusLost Autocommands for \"*.norg\": Vim(append):Error executing lua callback: vim/_editor.lua:0: FocusLost Autocommands for \"*.norg\"..script nvim_exec2() called at FocusLost Autocommands for \"*.norg\":0: Vim:E492: Not an editor command: Neorg tangle current-file\nstack traceback:\n\t[C]: in function 'nvim_exec2'\n\tvim/_editor.lua: in function 'cmd'\n\t/home/refaelsh/.config/nvim/init.lua:120: in function </home/refaelsh/.config/nvim/init.lua:119>")'. (File: src/bridge/ui_commands.rs; Line: 149, Column: 18)
   0: neovide::main::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: tokio::runtime::task::core::Core<T,S>::poll
   8: tokio::runtime::task::raw::poll
   9: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  10: tokio::runtime::task::raw::poll
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: std::sys::unix::thread::Thread::new::thread_start
  14: start_thread
  15: __GI___clone3

2023-12-25 19:14:43 - Neovide panicked with the message 'Focus Lost Failed: NeovimError(Some(0), "FocusLost Autocommands for \"*.norg\": Vim(append):Error executing lua callback: vim/_editor.lua:0: FocusLost Autocommands for \"*.norg\"..script nvim_exec2() called at FocusLost Autocommands for \"*.norg\":0: Vim:E492: Not an editor command: Neorg tangle current-file\nstack traceback:\n\t[C]: in function 'nvim_exec2'\n\tvim/_editor.lua: in function 'cmd'\n\t/home/refaelsh/.config/nvim/init.lua:120: in function </home/refaelsh/.config/nvim/init.lua:119>")'. (File: src/bridge/ui_commands.rs; Line: 149, Column: 18)
   0: neovide::main::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: tokio::runtime::task::core::Core<T,S>::poll
   8: tokio::runtime::task::raw::poll
   9: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  10: tokio::runtime::task::raw::poll
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: std::sys::unix::thread::Thread::new::thread_start
  14: start_thread
  15: __GI___clone3

2023-12-25 19:14:45 - Neovide panicked with the message 'Focus Lost Failed: NeovimError(Some(0), "FocusLost Autocommands for \"*.norg\": Vim(append):Error executing lua callback: vim/_editor.lua:0: FocusLost Autocommands for \"*.norg\"..script nvim_exec2() called at FocusLost Autocommands for \"*.norg\":0: Vim:E492: Not an editor command: Neorg tangle current-file\nstack traceback:\n\t[C]: in function 'nvim_exec2'\n\tvim/_editor.lua: in function 'cmd'\n\t/home/refaelsh/.config/nvim/init.lua:120: in function </home/refaelsh/.config/nvim/init.lua:119>")'. (File: src/bridge/ui_commands.rs; Line: 149, Column: 18)
   0: neovide::main::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: tokio::runtime::task::core::Core<T,S>::poll
   8: tokio::runtime::task::raw::poll
   9: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  10: tokio::runtime::task::raw::poll
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: std::sys::unix::thread::Thread::new::thread_start
  14: start_thread
  15: __GI___clone3

2023-12-25 19:14:48 - Neovide panicked with the message 'Focus Lost Failed: NeovimError(Some(0), "FocusLost Autocommands for \"*.norg\": Vim(append):Error executing lua callback: vim/_editor.lua:0: FocusLost Autocommands for \"*.norg\"..script nvim_exec2() called at FocusLost Autocommands for \"*.norg\":0: Vim:E492: Not an editor command: Neorg tangle current-file\nstack traceback:\n\t[C]: in function 'nvim_exec2'\n\tvim/_editor.lua: in function 'cmd'\n\t/home/refaelsh/.config/nvim/init.lua:120: in function </home/refaelsh/.config/nvim/init.lua:119>")'. (File: src/bridge/ui_commands.rs; Line: 149, Column: 18)
   0: neovide::main::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: tokio::runtime::task::core::Core<T,S>::poll
   8: tokio::runtime::task::raw::poll
   9: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  10: tokio::runtime::task::raw::poll
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: std::sys::unix::thread::Thread::new::thread_start
  14: start_thread
  15: __GI___clone3

2023-12-25 19:15:07 - Neovide panicked with the message 'Focus Lost Failed: NeovimError(Some(0), "FocusLost Autocommands for \"*.norg\": Vim(append):Error executing lua callback: vim/_editor.lua:0: FocusLost Autocommands for \"*.norg\"..script nvim_exec2() called at FocusLost Autocommands for \"*.norg\":0: Vim:E492: Not an editor command: Neorg tangle current-file\nstack traceback:\n\t[C]: in function 'nvim_exec2'\n\tvim/_editor.lua: in function 'cmd'\n\t/home/refaelsh/.config/nvim/init.lua:120: in function </home/refaelsh/.config/nvim/init.lua:119>")'. (File: src/bridge/ui_commands.rs; Line: 149, Column: 18)
   0: neovide::main::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: tokio::runtime::task::core::Core<T,S>::poll
   8: tokio::runtime::task::raw::poll
   9: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  10: tokio::runtime::task::raw::poll
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: std::sys::unix::thread::Thread::new::thread_start
  14: start_thread
  15: __GI___clone3

2023-12-25 19:15:10 - Neovide panicked with the message 'Focus Lost Failed: NeovimError(Some(0), "FocusLost Autocommands for \"*.norg\": Vim(append):Error executing lua callback: vim/_editor.lua:0: FocusLost Autocommands for \"*.norg\"..script nvim_exec2() called at FocusLost Autocommands for \"*.norg\":0: Vim:E492: Not an editor command: Neorg tangle current-file\nstack traceback:\n\t[C]: in function 'nvim_exec2'\n\tvim/_editor.lua: in function 'cmd'\n\t/home/refaelsh/.config/nvim/init.lua:120: in function </home/refaelsh/.config/nvim/init.lua:119>")'. (File: src/bridge/ui_commands.rs; Line: 149, Column: 18)
   0: neovide::main::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: tokio::runtime::task::core::Core<T,S>::poll
   8: tokio::runtime::task::raw::poll
   9: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  10: tokio::runtime::task::raw::poll
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: std::sys::unix::thread::Thread::new::thread_start
  14: start_thread
  15: __GI___clone3

2023-12-25 19:15:17 - Neovide panicked with the message 'Focus Lost Failed: NeovimError(Some(0), "FocusLost Autocommands for \"*.norg\": Vim(append):Error executing lua callback: vim/_editor.lua:0: FocusLost Autocommands for \"*.norg\"..script nvim_exec2() called at FocusLost Autocommands for \"*.norg\":0: Vim:E492: Not an editor command: Neorg tangle current-file\nstack traceback:\n\t[C]: in function 'nvim_exec2'\n\tvim/_editor.lua: in function 'cmd'\n\t/home/refaelsh/.config/nvim/init.lua:120: in function </home/refaelsh/.config/nvim/init.lua:119>")'. (File: src/bridge/ui_commands.rs; Line: 149, Column: 18)
   0: neovide::main::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: tokio::runtime::task::core::Core<T,S>::poll
   8: tokio::runtime::task::raw::poll
   9: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  10: tokio::runtime::task::raw::poll
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: std::sys::unix::thread::Thread::new::thread_start
  14: start_thread
  15: __GI___clone3

2023-12-25 19:16:57 - Neovide panicked with the message 'Focus Lost Failed: DecodeError(ReaderError(Custom { kind: UnexpectedEof, error: "EOF" }), "nvim_command")'. (File: src/bridge/ui_commands.rs; Line: 149, Column: 18)
   0: neovide::main::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: tokio::runtime::task::core::Core<T,S>::poll
   8: tokio::runtime::task::raw::poll
   9: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  10: tokio::runtime::task::raw::poll
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: std::sys::unix::thread::Thread::new::thread_start
  14: start_thread
  15: __GI___clone3

2023-12-25 19:17:46 - Neovide panicked with the message 'Focus Lost Failed: NeovimError(Some(0), "FocusLost Autocommands for \"*.norg\": Vim(append):Error executing lua callback: vim/_editor.lua:0: FocusLost Autocommands for \"*.norg\"..script nvim_exec2() called at FocusLost Autocommands for \"*.norg\":0: Vim:E492: Not an editor command: Neorg tangle current-file\nstack traceback:\n\t[C]: in function 'nvim_exec2'\n\tvim/_editor.lua: in function 'cmd'\n\t/home/refaelsh/.config/nvim/init.lua:120: in function </home/refaelsh/.config/nvim/init.lua:119>")'. (File: src/bridge/ui_commands.rs; Line: 149, Column: 18)
   0: neovide::main::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: tokio::runtime::task::core::Core<T,S>::poll
   8: tokio::runtime::task::raw::poll
   9: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  10: tokio::runtime::task::raw::poll
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: std::sys::unix::thread::Thread::new::thread_start
  14: start_thread
  15: __GI___clone3

2023-12-25 19:17:56 - Neovide panicked with the message 'Focus Lost Failed: NeovimError(Some(0), "FocusLost Autocommands for \"*.norg\": Vim(append):Error executing lua callback: vim/_editor.lua:0: FocusLost Autocommands for \"*.norg\"..script nvim_exec2() called at FocusLost Autocommands for \"*.norg\":0: Vim:E492: Not an editor command: Neorg tangle current-file\nstack traceback:\n\t[C]: in function 'nvim_exec2'\n\tvim/_editor.lua: in function 'cmd'\n\t/home/refaelsh/.config/nvim/init.lua:120: in function </home/refaelsh/.config/nvim/init.lua:119>")'. (File: src/bridge/ui_commands.rs; Line: 149, Column: 18)
   0: neovide::main::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: tokio::runtime::task::core::Core<T,S>::poll
   8: tokio::runtime::task::raw::poll
   9: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  10: tokio::runtime::task::raw::poll
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: std::sys::unix::thread::Thread::new::thread_start
  14: start_thread
  15: __GI___clone3

2023-12-25 19:17:56 - Neovide panicked with the message 'Focus Lost Failed: DecodeError(ReaderError(Custom { kind: UnexpectedEof, error: "EOF" }), "nvim_command")'. (File: src/bridge/ui_commands.rs; Line: 149, Column: 18)
   0: neovide::main::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: tokio::runtime::task::core::Core<T,S>::poll
   8: tokio::runtime::task::raw::poll
   9: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  10: tokio::runtime::task::raw::poll
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: std::sys::unix::thread::Thread::new::thread_start
  14: start_thread
  15: __GI___clone3

2023-12-25 19:20:51 - Neovide panicked with the message 'Focus Lost Failed: NeovimError(Some(0), "FocusLost Autocommands for \"*.norg\": Vim(append):Error executing lua callback: vim/_editor.lua:0: FocusLost Autocommands for \"*.norg\"..script nvim_exec2() called at FocusLost Autocommands for \"*.norg\":0: Vim:E492: Not an editor command: Neorg tangle current-file\nstack traceback:\n\t[C]: in function 'nvim_exec2'\n\tvim/_editor.lua: in function 'cmd'\n\t/home/refaelsh/.config/nvim/init.lua:120: in function </home/refaelsh/.config/nvim/init.lua:119>")'. (File: src/bridge/ui_commands.rs; Line: 149, Column: 18)
   0: neovide::main::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: tokio::runtime::task::core::Core<T,S>::poll
   8: tokio::runtime::task::raw::poll
   9: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  10: tokio::runtime::task::raw::poll
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: std::sys::unix::thread::Thread::new::thread_start
  14: start_thread
  15: __GI___clone3

2023-12-25 19:21:03 - Neovide panicked with the message 'Focus Lost Failed: NeovimError(Some(0), "FocusLost Autocommands for \"*.norg\": Vim(append):Error executing lua callback: vim/_editor.lua:0: FocusLost Autocommands for \"*.norg\"..script nvim_exec2() called at FocusLost Autocommands for \"*.norg\":0: Vim:E492: Not an editor command: Neorg tangle current-file\nstack traceback:\n\t[C]: in function 'nvim_exec2'\n\tvim/_editor.lua: in function 'cmd'\n\t/home/refaelsh/.config/nvim/init.lua:120: in function </home/refaelsh/.config/nvim/init.lua:119>")'. (File: src/bridge/ui_commands.rs; Line: 149, Column: 18)
   0: neovide::main::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: tokio::runtime::task::core::Core<T,S>::poll
   8: tokio::runtime::task::raw::poll
   9: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  10: tokio::runtime::task::raw::poll
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: std::sys::unix::thread::Thread::new::thread_start
  14: start_thread
  15: __GI___clone3

2023-12-25 19:21:03 - Neovide panicked with the message 'Focus Lost Failed: DecodeError(ReaderError(Custom { kind: UnexpectedEof, error: "EOF" }), "nvim_command")'. (File: src/bridge/ui_commands.rs; Line: 149, Column: 18)
   0: neovide::main::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: tokio::runtime::task::core::Core<T,S>::poll
   8: tokio::runtime::task::raw::poll
   9: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  10: tokio::runtime::task::raw::poll
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: std::sys::unix::thread::Thread::new::thread_start
  14: start_thread
  15: __GI___clone3

2023-12-25 19:21:52 - Neovide panicked with the message 'Focus Lost Failed: NeovimError(Some(0), "FocusLost Autocommands for \"*.norg\": Vim(append):Error executing lua callback: vim/_editor.lua:0: FocusLost Autocommands for \"*.norg\"..script nvim_exec2() called at FocusLost Autocommands for \"*.norg\":0: Vim:E492: Not an editor command: Neorg tangle current-file\nstack traceback:\n\t[C]: in function 'nvim_exec2'\n\tvim/_editor.lua: in function 'cmd'\n\t/home/refaelsh/.config/nvim/init.lua:120: in function </home/refaelsh/.config/nvim/init.lua:119>")'. (File: src/bridge/ui_commands.rs; Line: 149, Column: 18)
   0: neovide::main::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: tokio::runtime::task::core::Core<T,S>::poll
   8: tokio::runtime::task::raw::poll
   9: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  10: tokio::runtime::task::raw::poll
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: std::sys::unix::thread::Thread::new::thread_start
  14: start_thread
  15: __GI___clone3

2023-12-25 19:22:11 - Neovide panicked with the message 'Focus Lost Failed: NeovimError(Some(0), "FocusLost Autocommands for \"*.norg\": Vim(append):Error executing lua callback: vim/_editor.lua:0: FocusLost Autocommands for \"*.norg\"..script nvim_exec2() called at FocusLost Autocommands for \"*.norg\":0: Vim:E492: Not an editor command: Neorg tangle current-file\nstack traceback:\n\t[C]: in function 'nvim_exec2'\n\tvim/_editor.lua: in function 'cmd'\n\t/home/refaelsh/.config/nvim/init.lua:120: in function </home/refaelsh/.config/nvim/init.lua:119>")'. (File: src/bridge/ui_commands.rs; Line: 149, Column: 18)
   0: neovide::main::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: tokio::runtime::task::core::Core<T,S>::poll
   8: tokio::runtime::task::raw::poll
   9: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  10: tokio::runtime::task::raw::poll
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: std::sys::unix::thread::Thread::new::thread_start
  14: start_thread
  15: __GI___clone3

2023-12-25 19:22:11 - Neovide panicked with the message 'Focus Lost Failed: DecodeError(ReaderError(Custom { kind: UnexpectedEof, error: "EOF" }), "nvim_command")'. (File: src/bridge/ui_commands.rs; Line: 149, Column: 18)
   0: neovide::main::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: tokio::runtime::task::core::Core<T,S>::poll
   8: tokio::runtime::task::raw::poll
   9: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  10: tokio::runtime::task::raw::poll
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: std::sys::unix::thread::Thread::new::thread_start
  14: start_thread
  15: __GI___clone3

2023-12-25 19:31:28 - Neovide panicked with the message 'Focus Lost Failed: NeovimError(Some(0), "FocusLost Autocommands for \"*.norg\": Vim(append):Error executing lua callback: vim/_editor.lua:0: FocusLost Autocommands for \"*.norg\"..script nvim_exec2() called at FocusLost Autocommands for \"*.norg\":0: Vim:E492: Not an editor command: Neorg tangle current-file\nstack traceback:\n\t[C]: in function 'nvim_exec2'\n\tvim/_editor.lua: in function 'cmd'\n\t/home/refaelsh/.config/nvim/init.lua:120: in function </home/refaelsh/.config/nvim/init.lua:119>")'. (File: src/bridge/ui_commands.rs; Line: 149, Column: 18)
   0: neovide::main::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: tokio::runtime::task::core::Core<T,S>::poll
   8: tokio::runtime::task::raw::poll
   9: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  10: tokio::runtime::task::raw::poll
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: std::sys::unix::thread::Thread::new::thread_start
  14: start_thread
  15: __GI___clone3

2023-12-25 19:32:00 - Neovide panicked with the message 'Focus Lost Failed: NeovimError(Some(0), "FocusLost Autocommands for \"*.norg\": Vim(append):Error executing lua callback: vim/_editor.lua:0: FocusLost Autocommands for \"*.norg\"..script nvim_exec2() called at FocusLost Autocommands for \"*.norg\":0: Vim:E492: Not an editor command: Neorg tangle current-file\nstack traceback:\n\t[C]: in function 'nvim_exec2'\n\tvim/_editor.lua: in function 'cmd'\n\t/home/refaelsh/.config/nvim/init.lua:120: in function </home/refaelsh/.config/nvim/init.lua:119>")'. (File: src/bridge/ui_commands.rs; Line: 149, Column: 18)
   0: neovide::main::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: tokio::runtime::task::core::Core<T,S>::poll
   8: tokio::runtime::task::raw::poll
   9: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  10: tokio::runtime::task::raw::poll
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: std::sys::unix::thread::Thread::new::thread_start
  14: start_thread
  15: __GI___clone3

2023-12-25 19:32:19 - Neovide panicked with the message 'Focus Lost Failed: NeovimError(Some(0), "FocusLost Autocommands for \"*.norg\": Vim(append):Error executing lua callback: vim/_editor.lua:0: FocusLost Autocommands for \"*.norg\"..script nvim_exec2() called at FocusLost Autocommands for \"*.norg\":0: Vim:E492: Not an editor command: Neorg tangle current-file\nstack traceback:\n\t[C]: in function 'nvim_exec2'\n\tvim/_editor.lua: in function 'cmd'\n\t/home/refaelsh/.config/nvim/init.lua:120: in function </home/refaelsh/.config/nvim/init.lua:119>")'. (File: src/bridge/ui_commands.rs; Line: 149, Column: 18)
   0: neovide::main::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: tokio::runtime::task::core::Core<T,S>::poll
   8: tokio::runtime::task::raw::poll
   9: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  10: tokio::runtime::task::raw::poll
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: std::sys::unix::thread::Thread::new::thread_start
  14: start_thread
  15: __GI___clone3

2023-12-25 19:35:18 - Neovide panicked with the message 'Focus Lost Failed: NeovimError(Some(0), "FocusLost Autocommands for \"*.norg\": Vim(append):Error executing lua callback: vim/_editor.lua:0: FocusLost Autocommands for \"*.norg\"..script nvim_exec2() called at FocusLost Autocommands for \"*.norg\":0: Vim:E492: Not an editor command: Neorg tangle current-file\nstack traceback:\n\t[C]: in function 'nvim_exec2'\n\tvim/_editor.lua: in function 'cmd'\n\t/home/refaelsh/.config/nvim/init.lua:120: in function </home/refaelsh/.config/nvim/init.lua:119>")'. (File: src/bridge/ui_commands.rs; Line: 149, Column: 18)
   0: neovide::main::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: tokio::runtime::task::core::Core<T,S>::poll
   8: tokio::runtime::task::raw::poll
   9: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  10: tokio::runtime::task::raw::poll
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: std::sys::unix::thread::Thread::new::thread_start
  14: start_thread
  15: __GI___clone3

2023-12-25 19:35:32 - Neovide panicked with the message 'Focus Lost Failed: NeovimError(Some(0), "FocusLost Autocommands for \"*.norg\": Vim(append):Error executing lua callback: vim/_editor.lua:0: FocusLost Autocommands for \"*.norg\"..script nvim_exec2() called at FocusLost Autocommands for \"*.norg\":0: Vim:E492: Not an editor command: Neorg tangle current-file\nstack traceback:\n\t[C]: in function 'nvim_exec2'\n\tvim/_editor.lua: in function 'cmd'\n\t/home/refaelsh/.config/nvim/init.lua:120: in function </home/refaelsh/.config/nvim/init.lua:119>")'. (File: src/bridge/ui_commands.rs; Line: 149, Column: 18)
   0: neovide::main::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: tokio::runtime::task::core::Core<T,S>::poll
   8: tokio::runtime::task::raw::poll
   9: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  10: tokio::runtime::task::raw::poll
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: std::sys::unix::thread::Thread::new::thread_start
  14: start_thread
  15: __GI___clone3

2023-12-25 19:35:32 - Neovide panicked with the message 'Focus Lost Failed: DecodeError(ReaderError(Custom { kind: UnexpectedEof, error: "EOF" }), "nvim_command")'. (File: src/bridge/ui_commands.rs; Line: 149, Column: 18)
   0: neovide::main::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: tokio::runtime::task::core::Core<T,S>::poll
   8: tokio::runtime::task::raw::poll
   9: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  10: tokio::runtime::task::raw::poll
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: std::sys::unix::thread::Thread::new::thread_start
  14: start_thread
  15: __GI___clone3

2023-12-25 19:35:32 - Neovide panicked with the message 'Focus Lost Failed: DecodeError(ReaderError(Custom { kind: UnexpectedEof, error: "EOF" }), "nvim_command")'. (File: src/bridge/ui_commands.rs; Line: 149, Column: 18)
   0: neovide::main::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: tokio::runtime::task::core::Core<T,S>::poll
   8: tokio::runtime::task::raw::poll
   9: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  10: tokio::runtime::task::raw::poll
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: std::sys::unix::thread::Thread::new::thread_start
  14: start_thread
  15: __GI___clone3

2023-12-25 19:36:21 - Neovide panicked with the message 'Focus Lost Failed: NeovimError(Some(0), "FocusLost Autocommands for \"*.norg\": Vim(append):Error executing lua callback: vim/_editor.lua:0: FocusLost Autocommands for \"*.norg\"..script nvim_exec2() called at FocusLost Autocommands for \"*.norg\":0: Vim:E492: Not an editor command: Neorg tangle current-file\nstack traceback:\n\t[C]: in function 'nvim_exec2'\n\tvim/_editor.lua: in function 'cmd'\n\t/home/refaelsh/.config/nvim/init.lua:120: in function </home/refaelsh/.config/nvim/init.lua:119>")'. (File: src/bridge/ui_commands.rs; Line: 149, Column: 18)
   0: neovide::main::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: tokio::runtime::task::core::Core<T,S>::poll
   8: tokio::runtime::task::raw::poll
   9: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  10: tokio::runtime::task::raw::poll
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: std::sys::unix::thread::Thread::new::thread_start
  14: start_thread
  15: __GI___clone3

2023-12-25 19:36:29 - Neovide panicked with the message 'Focus Lost Failed: NeovimError(Some(0), "FocusLost Autocommands for \"*.norg\": Vim(append):Error executing lua callback: vim/_editor.lua:0: FocusLost Autocommands for \"*.norg\"..script nvim_exec2() called at FocusLost Autocommands for \"*.norg\":0: Vim:E492: Not an editor command: Neorg tangle current-file\nstack traceback:\n\t[C]: in function 'nvim_exec2'\n\tvim/_editor.lua: in function 'cmd'\n\t/home/refaelsh/.config/nvim/init.lua:120: in function </home/refaelsh/.config/nvim/init.lua:119>")'. (File: src/bridge/ui_commands.rs; Line: 149, Column: 18)
   0: neovide::main::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: tokio::runtime::task::core::Core<T,S>::poll
   8: tokio::runtime::task::raw::poll
   9: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  10: tokio::runtime::task::raw::poll
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: std::sys::unix::thread::Thread::new::thread_start
  14: start_thread
  15: __GI___clone3

2023-12-25 19:36:29 - Neovide panicked with the message 'Focus Gained Failed: NeovimError(Some(0), "Vim:Error executing vim.schedule lua callback: ...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/async.lua:85: The coroutine failed with this message: ...l/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/watcher.lua:69: attempt to index a nil value\nstack traceback:\n\t...l/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/watcher.lua: in function <...l/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/watcher.lua:65>\nstack traceback:\n\t[C]: in function 'error'\n\t...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/async.lua:85: in function 'cb'\n\t...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/async.lua:127: in function <...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/async.lua:126>")'. (File: src/bridge/ui_commands.rs; Line: 153, Column: 18)
   0: neovide::main::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: tokio::runtime::task::core::Core<T,S>::poll
   8: tokio::runtime::task::raw::poll
   9: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  10: tokio::runtime::task::raw::poll
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: std::sys::unix::thread::Thread::new::thread_start
  14: start_thread
  15: __GI___clone3

2023-12-25 19:36:29 - Neovide panicked with the message 'Focus Lost Failed: DecodeError(ReaderError(Custom { kind: UnexpectedEof, error: "EOF" }), "nvim_command")'. (File: src/bridge/ui_commands.rs; Line: 149, Column: 18)
   0: neovide::main::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: tokio::runtime::task::core::Core<T,S>::poll
   8: tokio::runtime::task::raw::poll
   9: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  10: tokio::runtime::task::raw::poll
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: std::sys::unix::thread::Thread::new::thread_start
  14: start_thread
  15: __GI___clone3

2023-12-25 19:37:26 - Neovide panicked with the message 'Focus Lost Failed: DecodeError(ReaderError(Custom { kind: UnexpectedEof, error: "EOF" }), "nvim_command")'. (File: src/bridge/ui_commands.rs; Line: 149, Column: 18)
   0: neovide::main::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: tokio::runtime::task::core::Core<T,S>::poll
   8: tokio::runtime::task::raw::poll
   9: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  10: tokio::runtime::task::raw::poll
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: std::sys::unix::thread::Thread::new::thread_start
  14: start_thread
  15: __GI___clone3

2023-12-25 19:38:28 - Neovide panicked with the message 'Focus Lost Failed: NeovimError(Some(0), "FocusLost Autocommands for \"*.norg\": Vim(append):Error executing lua callback: vim/_editor.lua:0: FocusLost Autocommands for \"*.norg\"..script nvim_exec2() called at FocusLost Autocommands for \"*.norg\":0: Vim:E492: Not an editor command: Neorg tangle current-file\nstack traceback:\n\t[C]: in function 'nvim_exec2'\n\tvim/_editor.lua: in function 'cmd'\n\t/home/refaelsh/.config/nvim/init.lua:120: in function </home/refaelsh/.config/nvim/init.lua:119>")'. (File: src/bridge/ui_commands.rs; Line: 149, Column: 18)
   0: neovide::main::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: tokio::runtime::task::core::Core<T,S>::poll
   8: tokio::runtime::task::raw::poll
   9: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  10: tokio::runtime::task::raw::poll
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: std::sys::unix::thread::Thread::new::thread_start
  14: start_thread
  15: __GI___clone3

2023-12-25 19:38:39 - Neovide panicked with the message 'Focus Lost Failed: NeovimError(Some(0), "FocusLost Autocommands for \"*.norg\": Vim(append):Error executing lua callback: vim/_editor.lua:0: FocusLost Autocommands for \"*.norg\"..script nvim_exec2() called at FocusLost Autocommands for \"*.norg\":0: Vim:E492: Not an editor command: Neorg tangle current-file\nstack traceback:\n\t[C]: in function 'nvim_exec2'\n\tvim/_editor.lua: in function 'cmd'\n\t/home/refaelsh/.config/nvim/init.lua:120: in function </home/refaelsh/.config/nvim/init.lua:119>")'. (File: src/bridge/ui_commands.rs; Line: 149, Column: 18)
   0: neovide::main::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: tokio::runtime::task::core::Core<T,S>::poll
   8: tokio::runtime::task::raw::poll
   9: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  10: tokio::runtime::task::raw::poll
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: std::sys::unix::thread::Thread::new::thread_start
  14: start_thread
  15: __GI___clone3

2023-12-25 19:38:39 - Neovide panicked with the message 'Focus Lost Failed: DecodeError(ReaderError(Custom { kind: UnexpectedEof, error: "EOF" }), "nvim_command")'. (File: src/bridge/ui_commands.rs; Line: 149, Column: 18)
   0: neovide::main::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: tokio::runtime::task::core::Core<T,S>::poll
   8: tokio::runtime::task::raw::poll
   9: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  10: tokio::runtime::task::raw::poll
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: std::sys::unix::thread::Thread::new::thread_start
  14: start_thread
  15: __GI___clone3

2023-12-25 21:17:53 - Neovide panicked with the message 'Focus Gained Failed: DecodeError(ReaderError(Custom { kind: UnexpectedEof, error: "EOF" }), "nvim_command")'. (File: src/bridge/ui_commands.rs; Line: 153, Column: 18)
   0: neovide::main::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: tokio::runtime::task::core::Core<T,S>::poll
   8: tokio::runtime::task::raw::poll
   9: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  10: tokio::runtime::task::raw::poll
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: std::sys::unix::thread::Thread::new::thread_start
  14: start_thread
  15: __GI___clone3

2024-08-21 19:13:08 - Neovide panicked with the message 'called `Result::unwrap()` on an `Err` value: Connection(IoError(Custom { kind: Other, error: UnknownError }))'. (File: /build/neovide-0.13.3-vendor.tar.gz/winit/src/platform_impl/linux/x11/window.rs; Line: 1316, Column: 14)
   0: neovide::main::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: winit::platform_impl::platform::x11::window::UnownedWindow::inner_size_physical
   8: winit::window::Window::inner_size
   9: neovide::window::update_loop::UpdateLoop::step
  10: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
  11: winit::platform_impl::platform::x11::EventLoop<T>::run_on_demand
  12: neovide::main
  13: std::sys_common::backtrace::__rust_begin_short_backtrace
  14: main
  15: __libc_start_call_main
  16: __libc_start_main@@GLIBC_2.34
  17: _start

2024-08-27 18:50:29 - Neovide panicked with the message 'called `Result::unwrap()` on an `Err` value: Connection(IoError(Custom { kind: Other, error: UnknownError }))'. (File: /build/neovide-0.13.3-vendor.tar.gz/winit/src/platform_impl/linux/x11/window.rs; Line: 1316, Column: 14)
   0: neovide::main::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: winit::platform_impl::platform::x11::window::UnownedWindow::inner_size_physical
   8: winit::window::Window::inner_size
   9: neovide::window::update_loop::UpdateLoop::step
  10: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
  11: winit::platform_impl::platform::x11::EventLoop<T>::run_on_demand
  12: neovide::main
  13: std::sys_common::backtrace::__rust_begin_short_backtrace
  14: main
  15: __libc_start_call_main
  16: __libc_start_main@@GLIBC_2.34
  17: _start

2024-08-29 06:04:11 - Neovide panicked with the message 'called `Result::unwrap()` on an `Err` value: Connection(IoError(Custom { kind: Other, error: UnknownError }))'. (File: /build/neovide-0.13.3-vendor.tar.gz/winit/src/platform_impl/linux/x11/window.rs; Line: 1316, Column: 14)
   0: neovide::main::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: winit::platform_impl::platform::x11::window::UnownedWindow::inner_size_physical
   8: winit::window::Window::inner_size
   9: neovide::window::update_loop::UpdateLoop::step
  10: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
  11: winit::platform_impl::platform::x11::EventLoop<T>::run_on_demand
  12: neovide::main
  13: std::sys_common::backtrace::__rust_begin_short_backtrace
  14: main
  15: __libc_start_call_main
  16: __libc_start_main@@GLIBC_2.34
  17: _start

2024-08-30 11:30:37 - Neovide panicked with the message 'called `Result::unwrap()` on an `Err` value: Connection(IoError(Custom { kind: Other, error: UnknownError }))'. (File: /build/neovide-0.13.3-vendor.tar.gz/winit/src/platform_impl/linux/x11/window.rs; Line: 1316, Column: 14)
   0: neovide::main::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: winit::platform_impl::platform::x11::window::UnownedWindow::inner_size_physical
   8: winit::window::Window::inner_size
   9: neovide::window::update_loop::UpdateLoop::step
  10: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
  11: winit::platform_impl::platform::x11::EventLoop<T>::run_on_demand
  12: neovide::main
  13: std::sys_common::backtrace::__rust_begin_short_backtrace
  14: main
  15: __libc_start_call_main
  16: __libc_start_main@@GLIBC_2.34
  17: _start

2024-08-30 11:52:00 - Neovide panicked with the message 'called `Result::unwrap()` on an `Err` value: Connection(IoError(Custom { kind: Other, error: UnknownError }))'. (File: /build/neovide-0.13.3-vendor.tar.gz/winit/src/platform_impl/linux/x11/window.rs; Line: 1316, Column: 14)
   0: neovide::main::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: winit::platform_impl::platform::x11::window::UnownedWindow::inner_size_physical
   8: winit::window::Window::inner_size
   9: neovide::window::update_loop::UpdateLoop::step
  10: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
  11: winit::platform_impl::platform::x11::EventLoop<T>::run_on_demand
  12: neovide::main
  13: std::sys_common::backtrace::__rust_begin_short_backtrace
  14: main
  15: __libc_start_call_main
  16: __libc_start_main@@GLIBC_2.34
  17: _start

